[Hardware]
# radar_cfg_file : Path to the Texas Instruments mmWave configuration file.
# cli_port       : Leave as "auto" to auto-detect, or specify exactly (COM for Windows, tty for Linux).
# data_port      : Leave as "auto" to auto-detect, or specify exactly (COM for Windows, tty for Linux).
radar_cfg_file = core/radar/config.cfg
cli_port = auto
data_port = auto

[Network]
# zmq_radar_port  : ZeroMQ port for broadcasting the live radar data.
# zmq_camera_port : ZeroMQ port for broadcasting the live camera feed.
zmq_radar_port = 5555
zmq_camera_port = 5556

[Recording]
# chunk_size : Number of frames to hold in RAM before writing to the hard drive. 
#              Adjust based on memory vs safety needs (100 is highly recommended).
chunk_size = 50

[Viewer]
# default_ip       : Default IP address of the Publisher (use 127.0.0.1 if running on the same machine).
# max_range_m      : Maximum physical distance to display on the Y-axis (in meters).
# cmap             : Colormap for the heatmap (options: inferno, viridis, plasma, magma, turbo, jet).
# low_pct          : Noise floor percentile (0 to 100) - hides background static and radar ghosting.
# high_pct         : Clipping percentile (0 to 100) - prevents extreme outliers from washing out the colors.
# smooth_grid_size : Resolution grid size for bilinear upscaling (makes blocky radar pixels look smooth).
default_ip = 127.0.0.1
max_range_m = 5.0
cmap = inferno
low_pct = 40.0
high_pct = 99.5
smooth_grid_size = 250

[Camera]
# width            : Camera capture width resolution (e.g., 640 or 1280).
# height           : Camera capture height resolution (e.g., 480 or 720).
# fps              : Target frames per second (e.g., 30 or 60).
# model_complexity : MediaPipe AI model complexity (0 = Lite/Fast, 1 = Normal, 2 = Heavy/Accurate).
# jpeg_quality     : Network stream compression quality (0 to 100). Lower numbers use less network bandwidth.
# auto_exposure    : True/False. False is highly recommended to prevent lighting flickers during AI tracking.
# exposure         : Manual exposure value (only applies if auto_exposure is False).
width = 640
height = 480
fps = 30
model_complexity = 1
jpeg_quality = 80
auto_exposure = False
exposure = 450

[Security]
server_public = iQ)F*U!qoiAD}1>Pi1>e5D+HT5izUFB}oC3(h%1D
server_secret = tK1^SBbPuGmHJEkg}[Pre2<<QSqvzA:e7TDjVcS%
client_public = Dt8+4?Sks%O}7SapncuWq%/QmGE-bp-<E?TrW#i[
client_secret = TNJ}{>lNH>.SPsz=CK2?X+n-C=E}px65t=mvUMz1