[theme]
primaryColor = "#0A8491"
base = "light"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#E8EEF2"
textColor = "#1E293B"
font = "sans serif"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[server]
headless = true 
runOnSave = false
address = "localhost"
showEmailPrompt = false
enableCORS = false
enableXsrfProtection = false
